import { Titillium_Web } from "next/font/google";
import "./globals.css";
import ThemeProvider, { ThemeContext, useTheme } from "@/contexts/themeContext";
import ThemeWrapper from "./components/ThemeWrapper";
import AuthProvider, { useAuth } from "@/contexts/auth/context";
import { useRouter } from "next/navigation";

const FONT = Titillium_Web({
  style: "normal",
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "LiveLoud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <ThemeWrapper>
        <body className={`bg-gray-100 dark:bg-gray-800 ${FONT.className}`}>
          <AuthProvider>{children}</AuthProvider>
        </body>
      </ThemeWrapper>
    </ThemeProvider>
  );
}
